// testing-vue/src/components/Counter.vue
<template>
  <div class="counter">
    <h3>Count up and down, but never below zero</h3>
    <p data-testid="count">{{ count }}</p>
    <div>
      <button type="button" aria-label="increase count" @click="increment">
        +1
      </button>
      <button type="button" aria-label="decrease count" @click="decrement">
        -1
      </button>
    </div>
    <button type="button" aria-label="reset count" @click="clear">
      reset
    </button>
  </div>
</template>

<script>
export default {
  props: {
    initialCount: {
      type: Number,
      default: 0
    },
    step: {
      type: Number,
      default: 1
    }
  },
  data() {
    return {
      count: this.initialCount
    };
  },
  methods: {
    increment() {
      this.count = this.count + this.step;
    },
    decrement() {
      this.count =
        this.count - this.step >= 0 ? this.count - this.step : this.count;
    },
    clear() {
      this.count = this.initialCount;
    }
  }
};
</script>

// testing-react/src/components/Counter.js
import React from 'react';
import useCounter from '../hooks/useCounter';
import StyledButton from './styled/StyledButton';

const Counter = ({ initialCount = 0 }) => {
  const { count, increment, decrement, clear } = useCounter(initialCount);

  return (
    <React.Fragment>
      <h3>Count up and down, but never below zero</h3>
      <p data-testid="count">{count}</p>
      <div>
        <StyledButton
          type="button"
          aria-label="increase count"
          onClick={increment}
        >
          +1
        </StyledButton>
        <StyledButton
          type="button"
          aria-label="decrease count"
          onClick={decrement}
        >
          -1
        </StyledButton>
      </div>
      <StyledButton type="button" aria-label="reset count" onClick={clear}>
        reset
      </StyledButton>
    </React.Fragment>
  );
};

export default Counter;
