// testing-vue/src/components/FetchExample.vue
<template>
  <div class="fetch-example">
    <h1>This is the fetch example page</h1>
    <h3 v-if="!userList">click here to fetch some users</h3>
    <button type="button" @click="fetchData" v-if="!userList">
      fetch users
    </button>
    <button type="button" @click="reset" v-else>reset users</button>
    <ul data-testid="userlist" class="userList" v-if="userList">
      <user v-for="user in userList" :key="user.id" :user="user" />
    </ul>
  </div>
</template>
<script>
import axios from "axios";
import user from "../components/User";
export default {
  components: { user },
  props: {
    url: {
      type: String,
      default: "https://jsonplaceholder.typicode.com/users"
    },
    options: {
      type: Object,
      default: null
    }
  },
  data() {
    return {
      userList: null
    };
  },
  methods: {
    async fetchData() {
      try {
        const res = await axios.get(this.url, this.options);
        this.userList = res.data;
      } catch (error) {
        console.error(error);
      }
    },
    reset() {
      this.userList = null;
    }
  }
};
</script>

<style>
.fetch-example {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}
.userList {
  display: flex;
  flex-direction: row;
  list-style-type: none;
  width: 80%;
  flex-wrap: wrap;
}
</style>

// testing-react/src/components/FetchExample.js
import React from 'react';
import styled from 'styled-components';
import User from './User';
import StyledButton from './styled/StyledButton';
import useApi from '../hooks/useApi';

const UserList = styled.ul`
  display: flex;
  flex-direction: row;
  list-style-type: none;
  width: 80%;
  flex-wrap: wrap;
`;

const FetchExample = ({
  url = 'https://jsonplaceholder.typicode.com/users',
}) => {
  const { response, fetchData, reset } = useApi(url);

  function renderButtons() {
    if (!response || response.length === 0) {
      return (
        <StyledButton type="button" onClick={fetchData}>
          fetch users
        </StyledButton>
      );
    }

    return (
      <StyledButton type="button" onClick={reset}>
        reset users
      </StyledButton>
    );
  }

  function renderUserList() {
    if (!response || response.length === 0) return <p>there are no users</p>;
    return (
      <UserList data-testid="userlist">
        {response.map(user => (
          <User key={`user-${user.id}`} user={user} />
        ))}
      </UserList>
    );
  }

  return (
    <React.Fragment>
      {!response && <h3>click here to fetch some users</h3>}
      {renderButtons()}
      {renderUserList()}
    </React.Fragment>
  );
};

export default FetchExample;
